learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

#包含了项目中的应用程序的URL
urlpatterns = [
    path('admin/', admin.site.urls),	#定义了管理网站中请求的所有URL
    path('',include(('learning_logs.urls','learning_logs'),namespace='learning_logs')),
    path('users/',include('users.urls',namespace='users')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path	
from . import views		# . 表示当前的urls.py模块所在的文件夹

app_name='learning_logs'	#防止报错：'learning_logs' is not a registered namespace
urlpatterns = [
	#主页
	path('',views.index, name='index'),	#从起始到末尾查找字符串中是否有URL

	#显示所有的topics
	path('topics/', views.topics, name='topics'),

	#显示所有主题的详细条目
	path("topics/<topic_id>/", views.topic, name='topic'),
	#将topic_id作为该主题对应的URL

	#用于添加新主题的网页
	path("new_topic/", views.new_topic, name='new_topic'),

	#用于添加新条目的网页
	path("new_entry/<topic_id>/", views.new_entry, name='new_entry'),

	#用于编辑条目的网页
	path("edit_entry/<entry_id>/", views.edit_entry, name='edit_entry'),
]	
#这里注意是列表[]而不是{}，这样会报错：'set' object is not reversible

users/urls.py
"""为应用程序users定义URL模式"""

from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'users'

#修改模版路径
urlpatterns = [
	#登录页面
	path('login/',LoginView.as_view(template_name='users/login.html'),name='login'),

	#注销页面
	path('logout/', views.logout_view, name='logout'),

	#注册页面
	path('register/',views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
	""""用户记录的主题"""
	#主题名
	text = models.CharField(max_length=200)	#CharField用于指明该属性要在数据库预留多少空间
	#创建时间
	date_added = models.DateTimeField(auto_now_add=True)	#auto_now_add=True表示每创建一个新主题，Django会自动将该属性设置为当前系统的时间
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	def __str__(self):
		#返回模型的字符串表示
		return self.text


class Entry(models.Model):
	"""每个主题下的记录条目"""
	topic = models.ForeignKey('Topic',on_delete=models.CASCADE)	#设置外键
	text = models.TextField()	#每条记录下的文本内容无长度限制
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		"""存储用于管理模型的额外信息，让Django在需要时使用entries在表示多个记录(而不是Entrys)"""
		verbose_name_plural = 'entries'

	def __str__(self):
		#返回模型的字符串表示(只显示前50个字符)
		return self.text[:50]+"..."	#...表示显示的非整个条目

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
"""定义面向用户的表单格式化"""

from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text' : ''}		#不要为text生成标签


class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text' : ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}		#设置HTML中部件大小
		

learning_logs/views.py
"""Tips: 将model和view分开编写，对应数据库中三层数据模型的抽象结构"""

from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic,Entry
from .forms import TopicForm, EntryForm

# Create your views here.

#为主页编写视图
def index(request):
	"""笔记的主页"""
	return render(request,'learning_logs/index.html')
	

@login_required 	#装饰器：检查用户是否已经登录，仅在用户登录时才运行topic()4
def topics(request):
	"""显示所有的主题"""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')	#按日期排序
	context = {'topics':topics}
	return render(request, 'learning_logs/topics.html', context)


@login_required 
def topic(request, topic_id):
	"""显示单个主题及其所有的条目内容"""
	topic = Topic.objects.get(id=topic_id)
	#确认请求的主题属于当前用户
	if topic.owner != request.user:
		#服务器上没有请求的资源时，返回404响应
		raise Http404

	entries = topic.entry_set.order_by('-date_added')
	context = {'topic':topic, 'entries':entries}
	return render(request, 'learning_logs/topic.html', context)


@login_required 
def new_topic(request):
	"""添加新主题"""
	if request.method != 'POST':
		#未提交数据，创建一个新表单
		form = TopicForm()
	else:
		#POST提交的数据，对数据进行处理
		form = TopicForm(request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))

	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)


@login_required 
def new_entry(request, topic_id):
	"""添加新条目"""
	topic = Topic.objects.get(id=topic_id)

	if request.method != 'POST':
		#未提交数据，创建一个空表单
		form = EntryForm()
	else:
		#POST提交数据了，对该数据进行处理
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

	context = {'topic': topic, 'form':form}
	return render(request, 'learning_logs/new_entry.html', context)


@login_required 
def edit_entry(request, entry_id):
	"""编辑已有条目"""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		#第一次请求，使用当前条目内容填充表单
		form = EntryForm(instance=entry)
	else:
		#POST提交的数据，对数据进行处理
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'learning_logs/edit_entry.html', context)


users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
# from django.utils.datastructures import MultiValueDictKeyError

# Create your views here.

def logout_view(request):
	"""注销用户"""
	logout(request)
	return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
	"""注册新用户"""
	if request.method != 'POST':
		#显示空的注册表单
		form = UserCreationForm
	else:
		#处理填好的表单
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			#让用户自动登录，再重定向到主页
			authenticated_user = authenticate(username=new_user.username,
				password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('learning_logs:index'))

	context = {'form': form}
	return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<!-- 该模版为其余网页的父模版 -->
<!-- 生成一个URL -->
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Learning Log</title>

		{% bootstrap_css %}
		{% bootstrap_javascript %}
	
	</head>

  <body>

	<!-- Static navbar -->
	<nav class="navbar navbar-default navbar-static-top">
	  <div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"></button>
			<a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
		</div>

		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
			</ul>

		<ul class="nav navbar-nav navbar-right">
			{% if user.is_authenticated %}
				<li><a>Hello, {{ user.username }}.</a></li>
				<li><a href="{% url 'users:logout' %}">log out</a></li>
			{% else %}
				<li><a href="{% url 'users:register' %}">register</a></li>
				<li><a href="{% url 'users:login' %}">log in</a></li>
			{% endif %}
		</ul>
		</div><!--/.nav-collapse -->
	  </div>
	</nav>

	<div class="container">
	  <div class="page-header">
	  	{% block header %}{% endblock header %}
	  </div>
	  <div>
	  	{% block content %}{% endblock content %}
	  </div>
	</div>  <!-- container -->

  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

	<p>Edit entry:</p>
	<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">save changes</button>
	</form>	
	
{% endblock content %}

learning_logs/templates/learning_logs/index.html
<!-- 父模板会显示相应网页的标题 -->
{% extends "learning_logs/base.html" %}	

<!-- hx用来标识字符大小，如h1,h2,h3... -->
{% block header %}
  <div class='jumbotron'>
  	<h3>Track your life. </h3>
  </div>
{% endblock header %}

{% block content %}
  <h2>
  	<a href="{% url 'users:register' %}">Register an account</a> to make your own Life&Learning Log, and list the topics you're learning about.
  </h2>
  <h2>
  	Whenever you learn something new about a topic, make an entry summarizing what you've learned.
  </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

	<p>Add a new entry:</p>
	<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">add entry</button>
	</form>	
	
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new topic:</h2>
{% endblock header%}


{% block content %}
	<form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
			<button name="submit" class="btn btn-primary">add topic</button>
		{% endbuttons %}
	</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}


{% block content %}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  </p>
  
  {% for entry in entries %}
     <div class="panel panel-default">
     <div class="panel-heading">
	    <h3>
		  {{ entry.date_added|date:'M d, Y H:i' }}
		  <!-- small将edit entry设置的大小小于时间戳 -->
	 	  <small>
			<a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
		  </small>
		</h3>
	  </div>
		<div class="panel-body">
		  {{ entry.text|linebreaks }}
		</div>
	</div> <!-- panel -->
  {% empty %}
	There are no entries for this topic yet.
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}
  <ul>
    {% for topic in topics %}
	  <li>
		<h4>
		  <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
		</h4>
	  </li>
	{% empty %}
	  <li>No topics have been added yet.</li>
	{% endfor %}
  </ul>
  
  <h3><a href="{% url 'learning_logs:new_topic' %}">Add new topic</h3>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}


{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
  	{% csrf_token %}
  	<!-- as_p:Django在表单中正确地显示所有的字段，包括错误消息 -->
  	{{ form.as_p }}

  	<button name="submit">register</button>
  	<input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}